research_task:
  description: >
    Conduct thorough research on the topic of {topic} and gather relevant information
    based on the current year.
  expected_output: >
    A comprehensive bullet list summarizing the key findings from this year and insights related to the topic.
  agent: researcher

write_task:
  description: >
    Write a 100-word engaging article on the topic of {topic} based on the research findings.
  expected_output: >
    A well-structured article in bullets that effectively communicates the key points about the topic.
  agent: writer
  context:
    - research_task
